config/routes.rb
Rails.application.routes.draw do
  get 'todolists/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'top' => 'homes#top'
  post 'todolists' => 'todolists#create'
  get 'todolists' => 'todolists#index'
  get 'todolists/:id' => 'todolists#show', as: 'todolist'
  get 'todolists/:id/edit' => 'todolists#edit', as: 'edit_todolist'
  patch 'todolists/:id' => 'todolists#update', as: 'update_todolist'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/todolist_controller.rb
class TodolistController < ApplicationController
  def new
    @list = List.new
  end

  def create
    list = List.new(list_params)
    list.save
    redirect_to '/top'
  end

  private
  def list_params
    params.require(:list).permit(:title, :body)
  end
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  def new
  end

  def create
    list = List.new(list_params)
    list.save
    redirect_to todolist_path(list.id)
  end

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    list = List.find(params[:id])
    list.update(list_params)
    redirect_to todolist_path(list.id)
  end

  def update
    list = List.find(params[:id])
    list_update(list_params)
    redirect_to todolist_path(list.id)
  end
  
  def destroy
    
  end

  private
  def list_params
    params.permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/todolist_helper.rb
module TodolistHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/homes/top.html.erb
<h1>ようこそBookersへ！</h1>
  <h4>Bookersでは、さまざまな書籍に関するあなたの意見や<br>
      印象を共有し交換することができます
  </h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todolists/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model:@list, url:"/todolists/#{@list.id}", local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <%= f.submit :'Update Book' %>

<% end %>

app/views/todolists/index.html.erb
<p id="notice">Book was successfully created.</p>
<% @lists.each do |list| %>
  <p>Title</p>
  <span>
    <%= link_to list.title, todolist_path(list.id) %>
  </span>
  <p>Body</p>
  <span>
    <%= link_to list.body, todolist_path(list.id) %>
  </span>
<% end %>

app/views/todolists/new.html.erb
<h1>New book</h1>
<%= form_with model: @list, url:'/todolists', local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/todolists/show.html.erb
<p id="notice">Book was successfully created.</p>
<h2>Title</h2>
<p><%= @list.title %></p>
<h2>Body</h2>
<p><%= @list.body %></p>
<%= link_to "Edit", edit_todolist_path(@list.id) %>